### ISSUE TITLE
A quick glance review

### ISSUE THREAD

**Issue by sudo-jaa** [simon-engledew/json-validator#1]
Hey, Darren mentioned you were interested in getting some extra eyes on this project. I did a quick glance over and found a couple of things that might be worth changing, but it's nothing major. if you feel like you might benefit from a more in-depth look i'm happy to spend a bit more time on it. 

---------------

- You've got a few instances of repeating the type you use for `HashMap<String, JsonSchema>`. This is probably a good candidate for a type alias to keep your function signatures a bit cleaner. 

  Defining it like this will help you avoid some of the guff in your functions: 
```
type SchemaMap = HashMap<String, JSONSchema>;
```

- You've got a lot of qualified imports inline. This might be a stylistic choice so fair play if that's the case. But if you throw things like `jsonschema::ValidationError` and `jsonschema::ErrorIterator` into the `use` at the top, you might find things a little cleaner. 

  You've also got a few redundant imports. You can remove `use log;` and `use serde_json;`

- As far as I can reasonably tell, dereferencing and then borrowing self in the display impl for LoadError is unecessary. Changing `match &*self` to `match self` seems to work just fine. 

- The parameter types for `load_schemas` feels a bit off to me. You use the trait and associated type for an input iterator when you can just use `Vec<String>`, especially as that's the only type that's actually provided to the function. You don't need to specify that trait bound as the compiler knows that a `Vec` implements `IntoIterator`. 

```
fn load_schemas<'a>(paths: impl IntoIterator<Item = String>)
```
```
fn load_schemas<'a>(paths: Vec<String>)
``` 

- On the topic of `load_schemas`, you've defined it as returning `Result<HashMap<String, JSONSchema>, LoadError<'a>>` which probably isn't necessary given that it always returns `Ok(SchemaMap)`. This might be because you havent implemented any error handling on it yet, or it might just be an oversight. But if this always returns a hashmap, whether it's full or not, with no error handling other than logging, then you can just change this.  You can then avoid checks to expect this value later down the line. 

```
fn load_schemas<'a>(paths: Vec<String>) -> SchemaMap
```

- Also, you don't need a lifetime specifier in `load_schemas`. So it can be even further simplified: 

```
fn load_schemas(paths: Vec<String>) -> SchemaMap {
```

- Also, this is bikeshed as fuck, but apparently the linter doesn't like variant names including the enum name itself. I guess this applies to `LoadError` having `ReadError`, `ParseError`, `CompileError`. It could be considered cleaner to just use the following, but that's super nitpicky 🤷 

```
enum LoadError<'a> {
    Read(&'a str, std::io::Error),
    Parse(&'a str, serde_json::Error),
    Compile(&'a str, std::string::String),
}
```

**Comment by simon-engledew** [comment]
Good feedback, thanks! 🙇 ❤️ 

Some of the stuff you mentioned was indeed wip, but the majority of your comments were super helpful! Thanks man, I owe you a beverage of your choice! 🍺
